substitutions:
  sensors: "false"

globals:
  - id: s3temp
    type: int
    initial_value: '0'
  - id: s_saver_presc
    type: int
    initial_value: '0'
  - id: battery_percent
    type: int
    initial_value: '0'
