substitutions:
  sensors: "false"

sensor:
  - platform: template
    id: s3temp
    lambda: return 0;
    update_interval: never
  - platform: template
    id: s_saver_presc
    lambda: return 0;
    update_interval: never
  - platform: template
    id: battery_percent
    lambda: return 0;
    update_interval: never
